### ISSUE TITLE
Error in Running Code due to Imports

### ISSUE THREAD

**Issue by medhahira** [will-rice/denoisers#11]
---------------------------------------------------------------------------
Hi! I was trying to run the code. When I tried to install the requirements, it gave me some import errors which I had to resolve through the following commands:
`
!pip install fastapi
`
`
!pip install kaleido
`
`
!pip install python-multipart
`
`
!pip install cohere
`
`
!pip install openai
`
`
!pip install tiktoken
`
Hope you can add these. However, on running the imports from the code in the README, I was getting the following error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-15-1b790f991d43>](https://localhost:8080/#) in <cell line: 3>()
      1 import torch
      2 import torchaudio
----> 3 from denoisers import WaveUNetModel
      4 from tqdm import tqdm

11 frames
[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/saving.py](https://localhost:8080/#) in <module>
     44     from omegaconf import OmegaConf
     45     from omegaconf.dictconfig import DictConfig
---> 46     from omegaconf.errors import UnsupportedValueType, ValidationError
     47 
     48 # the older shall be on the top

ImportError: cannot import name 'UnsupportedValueType' from 'omegaconf.errors' (/usr/local/lib/python3.10/dist-packages/omegaconf/errors.py)

Hope you can provide a fix as I needed immediate help in denoising my audio clips for a ASR project.

**Comment by will-rice** [comment]
Hi! Thanks for checking out the project. I'm in the process of updating the requirements. For your error specifically make sure the `pytorch-lightning` version matches the `torch` version. Currently, I'm using `torch 2.1.0` and `pytorch-lightning 2.1.0`

**Comment by will-rice** [comment]
@medhahira did you get this worked out?
