### ISSUE TITLE
AttributeError: 'WaveUNetModelOutputs' object has no attribute 'output'

### ISSUE THREAD

**Issue by karim23657** [will-rice/denoisers#22]
@will-rice , I just got this error,I attached my audio file: 
[p232.wav.zip](https://github.com/will-rice/denoisers/files/14550543/p232.wav.zip)

code: 
```python
import torch
import torchaudio
from denoisers import WaveUNetModel
from tqdm import tqdm

model = WaveUNetModel.from_pretrained("wrice/waveunet-vctk-24khz")

audio, sr = torchaudio.load("/content/p2325.wav")

if sr != model.config.sample_rate:
    audio = torchaudio.functional.resample(audio, sr, model.config.sample_rate)

chunk_size = model.config.max_length

padding = abs(audio.size(-1) % chunk_size - chunk_size)
padded = torch.nn.functional.pad(audio, (0, padding))

clean = []
for i in tqdm(range(0, padded.shape[-1], chunk_size)):
    audio_chunk = padded[:, i:i + chunk_size]
    with torch.no_grad():
        clean_chunk = model(audio_chunk[None]).audio
    clean.append(clean_chunk.squeeze(0))

denoised = torch.concat(clean, 1)[:, :audio.shape[-1]]
```

error: 
```shell
0%|          | 0/1 [00:01<?, ?it/s]

AttributeError        
[p232.wav.zip](https://github.com/will-rice/denoisers/files/14550543/p232.wav.zip)
                    Traceback (most recent call last)
     22         # a=model(audio_chunk[None])
     23         # print(a)
---> 24         clean_chunk = model(audio_chunk[None]).output.audio
     25         # clean_chunk = model(audio_chunk[None]).audio
     26     clean.append(clean_chunk.squeeze(0))

AttributeError: 'WaveUNetModelOutputs' object has no attribute 'output'

```

**Comment by will-rice** [comment]
it should be '.audio' not '.output.audio'

**Comment by karim23657** [comment]
@will-rice , I used `.audio` in my code, but in issue I pasted my previous console output here,
But now i attached a jupyter notebook to reproduce error:

 [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/gist/karim23657/fade56b0904d07366ed78619e154f725/denoisers_issue.ipynb)

this is test audio file:
[p232.wav.zip](https://github.com/will-rice/denoisers/files/14584278/p232.wav.zip)

**Comment by will-rice** [comment]
I didn't publish a new release with the `.audio` change. A work around is using `.logits` instead of `.audio` for version 0.1.6. I'm publishing a release right now with the correction. The latest version 0.1.7 will use `.audio`

**Comment by will-rice** [comment]
@karim23657 were you able to get this working?

**Comment by karim23657** [comment]
@will-rice , thank you . Now working.
```python
import IPython
IPython.display.Audio(denoised.numpy(), rate=model.config.sample_rate)
```
